spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/line_local?serverTimezone=Asia/Tokyo
    username: root
    password: ahihi123
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  threads:
    virtual:
      enabled: true
    pool-core-size: 10
    max-pool-size: 20
    queue-capacity: 500
line:
  bot:
    channel-token: "fXj9awxgDNWz4kQePeMa2p3feQXdeXgBM0njxymGHPmMq53p737D3qxtU1ECNVKdB353lK89nwoZTvSHl6lshUD11XFNMRMxoSWiTG2ql2UGkueIA9lHFEvIRFe//tYFyt6b6TmsmFEa96ZBppnB/AdB04t89/1O/w1cDnyilFU="
    channel-secret: "aa5d3156145d59dbceffa279469d18cb"
