spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/line_local?serverTimezone=Asia/Tokyo
    username: root
    password: ahihi123
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  threads:
    virtual:
      enabled: true
    pool-core-size: 10
    max-pool-size: 20
    queue-capacity: 500
    name-prefix: "mini-app-integration"
line:
  bot:
#    replace your channel token & channel secret
    channel-token: "replace your channel token"
    channel-secret: "replace your channel secret"
